config/routes.rb
Rails.application.routes.draw do
  resources :booklists

end

app/models/booklist.rb
class Booklist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/booklists_controller.rb
class BooklistsController < ApplicationController
  before_action :set_booklist, only: [:show, :edit, :update, :destroy]

  # GET /booklists
  # GET /booklists.json
  def index
    @booklists = Booklist.all
  end

  # GET /booklists/1
  # GET /booklists/1.json
  def show
  end

  # GET /booklists/new
  def new
    @booklist = Booklist.new
  end

  # GET /booklists/1/edit
  def edit
  end

  # POST /booklists
  # POST /booklists.json
  def create
    @booklist = Booklist.new(booklist_params)

    respond_to do |format|
      if @booklist.save
        format.html { redirect_to @booklist, notice: 'Booklist was successfully created.' }
        format.json { render :show, status: :created, location: @booklist }
      else
        format.html { render :new }
        format.json { render json: @booklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booklists/1
  # PATCH/PUT /booklists/1.json
  def update
    respond_to do |format|
      if @booklist.update(booklist_params)
        format.html { redirect_to @booklist, notice: 'Booklist was successfully updated.' }
        format.json { render :show, status: :ok, location: @booklist }
      else
        format.html { render :edit }
        format.json { render json: @booklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booklists/1
  # DELETE /booklists/1.json
  def aa
    @booklist.destroy
    respond_to do |format|
      format.html { redirect_to booklists_url, notice: 'Booklist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booklist
      @booklist = Booklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booklist_params
      params.require(:booklist).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booklists_helper.rb
module BooklistsHelper
end

app/views/booklists/_form.html.erb
<%= form_for(@booklist) do |f| %>
  <% if @booklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booklist.errors.count, "error") %> prohibited this booklist from being saved:</h2>

      <ul>
      <% @booklist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/booklists/edit.html.erb
<h1>Editing booklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @booklist %> |
<%= link_to 'Back', booklists_path %>

app/views/booklists/index.html.erb
<h1>Listing booklists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @booklists.each do |booklist| %>
      <tr>
        <td><%= booklist.title %></td>
        <td><%= link_to 'Show', booklist %></td>
        <td><%= link_to 'Edit', edit_booklist_path(booklist) %></td>
        <td><%= link_to 'Destroy', booklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booklist', new_booklist_path %>

app/views/booklists/new.html.erb
<h1>New booklist</h1>

<%= render 'form' %>

<%= link_to 'Back', booklists_path %>

app/views/booklists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @booklist.title %>
</p>

<%= link_to 'Edit', edit_booklist_path(@booklist) %> |
<%= link_to 'Back', booklists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>